builds:
  - binary: data
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goamd64:
      - v1
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -trimpath

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: data
    homepage: https://github.com/thientran2020/data
    tap:
      owner: thientran2020
      name: homebrew-thientran2020
    commit_author:
      name: thientran
      email: thienytran14@gmail.com

checksum:
  name_template: 'checksums.txt'